
[[main]]
  identifier = "work"
  name = "work"
  url = "work"
  weight = 1
    
[[main]]
  identifier = "privacy"
  name = "privacy"
  url = "privacy"
  weight = 2

[[main]]
  identifier = "tech"
  name = "tech"
  url = "tech"
  weight = 3	
