
[[main]]
  identifier = "work"
  name = "work"
  url = "work"
  weight = 1
    
[[main]]
  identifier = "privacyFAQs"
  name = "privacyFAQs"
  url = "privacyFAQs"
  weight = 2

[[main]]
  identifier = "tech"
  name = "tech"
  url = "tech"
  weight = 3	
